ALTER TABLE PhanHoi
DROP CONSTRAINT FK__PhanHoi__KhachHa__3F466844;

ALTER TABLE PhanHoi
ADD CONSTRAINT FK__PhanHoi__KhachHa__3F466844
FOREIGN KEY (KhachHangId) REFERENCES KhachHang(Id)
ON DELETE CASCADE;
ALTER TABLE LichSuDatDichVu
DROP CONSTRAINT FK__LichSuDat__Khach__440B1D61;

ALTER TABLE LichSuDatDichVu
ADD CONSTRAINT FK__LichSuDat__Khach__440B1D61
FOREIGN KEY (KhachHangId) REFERENCES KhachHang(Id)
ON DELETE CASCADE;
