// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebDichVu.Datas;

#nullable disable

namespace WebDichVu.Migrations
{
    [DbContext(typeof(ThuYcaKoiVetContext))]
    partial class ThuYcaKoiVetContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebDichVu.Datas.BacSiThuY", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChuyenMon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TenBacSi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__BacSiThu__3214EC07E1B97C42");

                    b.ToTable("BacSiThuY", (string)null);
                });

            modelBuilder.Entity("WebDichVu.Datas.DichVu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ChiPhiDiChuyen")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__DichVu__3214EC07CC5E9DE5");

                    b.ToTable("DichVu", (string)null);
                });

            modelBuilder.Entity("WebDichVu.Datas.KhachHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("Matkhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TenKhachHang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__KhachHan__3214EC07DD2E8CA9");

                    b.HasIndex(new[] { "SoDienThoai" }, "UQ__KhachHan__0389B7BD1161810E")
                        .IsUnique();

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("WebDichVu.Datas.LichHen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BacSiThuYid")
                        .HasColumnType("int");

                    b.Property<string>("DiaDiem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DichVuId")
                        .HasColumnType("int");

                    b.Property<int>("KhachHangId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BacSiThuYid");

                    b.HasIndex("DichVuId");

                    b.HasIndex("KhachHangId");

                    b.ToTable("LichHens");
                });

            modelBuilder.Entity("WebDichVu.Datas.LichLamViec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BacSiThuYid")
                        .HasColumnType("int")
                        .HasColumnName("BacSiThuYId");

                    b.Property<TimeOnly>("GioBatDau")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("GioKetThuc")
                        .HasColumnType("time");

                    b.Property<DateOnly>("Ngay")
                        .HasColumnType("date");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__LichLamV__3214EC077A680252");

                    b.HasIndex("BacSiThuYid");

                    b.ToTable("LichLamViec", (string)null);
                });

            modelBuilder.Entity("WebDichVu.Datas.LichSuDatDichVu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DichVuId")
                        .HasColumnType("int");

                    b.Property<int>("KhachHangId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGian")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__LichSuDa__3214EC0752EB358A");

                    b.HasIndex("DichVuId");

                    b.HasIndex("KhachHangId");

                    b.ToTable("LichSuDatDichVu", (string)null);
                });

            modelBuilder.Entity("WebDichVu.Datas.PhanHoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DichVuId")
                        .HasColumnType("int");

                    b.Property<int>("KhachHangId")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ThoiGian")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__PhanHoi__3214EC0718C47948");

                    b.HasIndex("DichVuId");

                    b.HasIndex("KhachHangId");

                    b.ToTable("PhanHoi", (string)null);
                });

            modelBuilder.Entity("WebDichVu.Datas.LichHen", b =>
                {
                    b.HasOne("WebDichVu.Datas.BacSiThuY", "BacSiThuY")
                        .WithMany("LichHens")
                        .HasForeignKey("BacSiThuYid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebDichVu.Datas.DichVu", "DichVu")
                        .WithMany("LichHens")
                        .HasForeignKey("DichVuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebDichVu.Datas.KhachHang", "KhachHang")
                        .WithMany("LichHens")
                        .HasForeignKey("KhachHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BacSiThuY");

                    b.Navigation("DichVu");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("WebDichVu.Datas.LichLamViec", b =>
                {
                    b.HasOne("WebDichVu.Datas.BacSiThuY", "BacSiThuY")
                        .WithMany("LichLamViecs")
                        .HasForeignKey("BacSiThuYid")
                        .IsRequired()
                        .HasConstraintName("FK__LichLamVi__BacSi__398D8EEE");

                    b.Navigation("BacSiThuY");
                });

            modelBuilder.Entity("WebDichVu.Datas.LichSuDatDichVu", b =>
                {
                    b.HasOne("WebDichVu.Datas.DichVu", "DichVu")
                        .WithMany("LichSuDatDichVus")
                        .HasForeignKey("DichVuId")
                        .IsRequired()
                        .HasConstraintName("FK__LichSuDat__DichV__31EC6D26");

                    b.HasOne("WebDichVu.Datas.KhachHang", "KhachHang")
                        .WithMany("LichSuDatDichVus")
                        .HasForeignKey("KhachHangId")
                        .IsRequired()
                        .HasConstraintName("FK__LichSuDat__Khach__30F848ED");

                    b.Navigation("DichVu");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("WebDichVu.Datas.PhanHoi", b =>
                {
                    b.HasOne("WebDichVu.Datas.DichVu", "DichVu")
                        .WithMany("PhanHois")
                        .HasForeignKey("DichVuId")
                        .IsRequired()
                        .HasConstraintName("FK__PhanHoi__DichVuI__2D27B809");

                    b.HasOne("WebDichVu.Datas.KhachHang", "KhachHang")
                        .WithMany("PhanHois")
                        .HasForeignKey("KhachHangId")
                        .IsRequired()
                        .HasConstraintName("FK__PhanHoi__KhachHa__2C3393D0");

                    b.Navigation("DichVu");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("WebDichVu.Datas.BacSiThuY", b =>
                {
                    b.Navigation("LichHens");

                    b.Navigation("LichLamViecs");
                });

            modelBuilder.Entity("WebDichVu.Datas.DichVu", b =>
                {
                    b.Navigation("LichHens");

                    b.Navigation("LichSuDatDichVus");

                    b.Navigation("PhanHois");
                });

            modelBuilder.Entity("WebDichVu.Datas.KhachHang", b =>
                {
                    b.Navigation("LichHens");

                    b.Navigation("LichSuDatDichVus");

                    b.Navigation("PhanHois");
                });
#pragma warning restore 612, 618
        }
    }
}
